# Generated by Django 6.0 on 2026-01-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='created_when',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
